### ISSUE TITLE
Proposal: loading environment variables from other types

### ISSUE THREAD

**Issue by sah4ez** [l-vitaly/goenv#3]
My environment variables may be configured from different formats. As example I can setting from `yaml` files.
```yaml
env:
 - NAME_VARIABLE1: "values1"
 - NAME_VARIABLE2: "values2"
```
And call this command, for generation `config.go`:
```bash
$ envgen -env values.yaml -field environment
```
If you can added some flags for parsing specific formats and fields it's will cool!
